// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMZcwnb1_6CzOiojALnEnBeM52fFJHyk',
    appId: '1:868265816686:ios:3ed636d20768aee00eac7f',
    messagingSenderId: '868265816686',
    projectId: 'homez-3ff90',
    storageBucket: 'homez-3ff90.firebasestorage.app',
    iosBundleId: 'com.example.homez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbMZcwnb1_6CzOiojALnEnBeM52fFJHyk',
    appId: '1:868265816686:ios:3ed636d20768aee00eac7f',
    messagingSenderId: '868265816686',
    projectId: 'homez-3ff90',
    storageBucket: 'homez-3ff90.firebasestorage.app',
    iosBundleId: 'com.example.homez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTC9-E6aV7BytrMy0w7E3ECRWN7QG3IkU',
    appId: '1:868265816686:web:9afe3e53fa6f7f630eac7f',
    messagingSenderId: '868265816686',
    projectId: 'homez-3ff90',
    authDomain: 'homez-3ff90.firebaseapp.com',
    storageBucket: 'homez-3ff90.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTC9-E6aV7BytrMy0w7E3ECRWN7QG3IkU',
    appId: '1:868265816686:web:9afe3e53fa6f7f630eac7f',
    messagingSenderId: '868265816686',
    projectId: 'homez-3ff90',
    authDomain: 'homez-3ff90.firebaseapp.com',
    storageBucket: 'homez-3ff90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoB10R2Rove4YvHBkCFXBYdKdgjz0indA',
    appId: '1:868265816686:android:8f7f3a11f4c4ebef0eac7f',
    messagingSenderId: '868265816686',
    projectId: 'homez-3ff90',
    storageBucket: 'homez-3ff90.firebasestorage.app',
  );

}